<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>.then and .catch PS</title>
</head>
<body>
    

    <script>
        // Q1: Write a program to load the js script file in a browser using promise and use .then .catch to display an alert when script is load 
        // const loadScript = async (src)=>{
        //     return new Promise((resolved , reject)=>{
        //         let script = document.createElement("script");
        //         script.src = src;
        //         script.onload=()=>{
        //             // alert("Script is loaded");
        //             resolved(`This src is loaded ${src}`);
        //         }
        //         document.body.appendChild(script)
        //     })
        // }

        // Q1 Solution
        // let a = loadScript("https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js");
        // a.then((res)=>{
        //     alert(res);
        // }).catch((err)=>{
        //     alert(err);
        // })

        // Q2: Write the same program usng async await func from previous program 
        // const loadScript = async(src)=>{
        //     return new Promise((resolved , reject)=>{
        //         let script = document.createElement("script");
        //         script.src = src;
        //         script.onload=()=>{
        //             resolved(`The script is loaded ${src}`)
        //         }
        //         document.body.appendChild(script);
        //     })
        // }

        // let a = loadScript("https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js");

        // const func = async ()=>{
        //     let result = await a;
        //     alert(result);
        // }

        // func();

        // Q3 : create a promise which is reject afetr 3 sec use an async/await to get its value use try catch to handle it error 
        let p =()=>{ 
            return new Promise((resolved , reject)=>{
            setTimeout(()=>{
                // reject(`The promise is rejected after 3 seconds`);
                reject(new Error("The promise is rejected after 3 seconds"));
            },3000)
        })
        }

        const a = async()=>{
            try{
                let c = await p();
                alert(c);
            }catch(err){
                alert(err);
            }
        }
        a();

        // Example of IIFE
        // (async()=>{
        //     let a = await p;
        //     console.log(a);
        // })();

        // Q4 : Write a program using promise.all() inside an async await 3 promises . compare its result with the   we await the promise one by one 
    </script>
</body>
</html>